<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/css" href="style1.css"?>
<!DOCTYPE person
 [
  <!ELEMENT person (person+)>
  <!ELEMENT person (name, phome, pwork, pmobile, email?)>
  <!ATTLIST person persID ID #REQUIRED>
  <!ELEMENT name (#PCDATA)>
  <!ATTLIST name title (Mr.|Mrs.|Ms.) #REQUIRED>
  <!ELEMENT phome (#PCDATA)>
  <!ELEMENT pwork (#PCDATA)>
  <!ELEMENT pmobile (#PCDATA)>
  <!ELEMENT email (#PCDATA)>
]>

<person>
  <person persID="pers101">
    <name title="Mr.">Rorie Demanche</name>
    <phome>+1 (710) 153-4949</phome>
    <pwork>+1 (503) 319-3558</pwork>
    <pmobile>+1 (182) 748-1667 </pmobile>
    <email>rdemanche0@foxnews.com</email>
  </person>

  <person>
  <person persID="pers102">
    <name title="Mr.">Kelcey Surman</name>
    <phome>+1 (249) 926-7376</phome>
    <pwork>+1 (208) 363-6588</pwork>
    <pmobile>+1 (982) 536-6860</pmobile>
    <email>ksurman1@usnews.com</email>
  </person>

  <person persID="pers103">
    <name title="Mr.">Simon Heddan</name>
    <phome>+1 (687) 808-4290</phome>
    <pwork>+1 (604) 815-7810</pwork>
    <pmobile>+1 (924) 174-3271</pmobile>
    <email>sheddan2@alexa.com</email>
  </person>

  <person persID="pers104">
    <name title="Mr.">Chan Supple</name>
    <phome>+1 (577) 165-2495</phome>
    <pwork>+1 (547) 934-7337</pwork>
    <pmobile>+1 (367) 667-0747</pmobile>
    <email>csupple3@123-reg.co.uk</email>
  </person>